apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service

  
spec:
  selector:
    app: pythonapp
  
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
