apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  labels:
    app: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: vishyswaminathan/python-image
        ports:
        -  name: pythonapp-port
           containerPort: 8080
#### testing a minor change to see if argo CD workds ####
